# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'drawernavigation'
  app.support_libraries << 'android-support-v7-appcompat'
  app.api_version = '23'
  app.target_api_version = '23'
  app.theme = "@style/Theme.AppCompat.Light.DarkActionBar"
end
